### ISSUE TITLE
duplo-1.6.19 fails test suite

### ISSUE THREAD

**Issue by peti** [pixbi/duplo#25]
Citing from http://hydra.cryp.to/build/527320/nixlog/1/raw:

```
running tests
Running 1 test suites...
Test suite tests: RUNNING...
Tests
  Component support
    slash is transformed into dash: FAIL (0.01s)
      *** Gave up! Passed only 86 tests.
    extracts component ID:          OK

1 out of 2 tests failed (0.01s)
Test suite tests: FAIL
```

**Comment by kenhkan** [comment]
@peti That's strange. Though the most recent version at v1.7.5 should be working. By the way, did you get duplo to run on hydra? I've been looking into using Nix for management but haven't quite found an intuitive way to use it. Do you happen to have any insight on that? Thanks.

**Comment by peti** [comment]
I believe this issue occurs in a test that has a `==>`-style precondition, and the random generator just happened to generate lots of samples that didn't fulfill that condition, so at some point it gave up to avoid running "forever". IMHO, the only way to avoid that corner case is to (a) use appropriately weak pre-conditions or, if that isn't possible, (b) write a `forAll`-style generator that constructs appropriate samples alll the time.

About you question: I'm not actually using duplo myself, I'm afraid, I just maintain the Haskell packages for Nix and thus came across the build error in our CI, so I can't say much about your question. Sorry!

**Comment by kenhkan** [comment]
Ah. Thanks for letting me know then! So I ran the tests again at v1.6.19, and I ran it again with 1 million test cases. It has run fine on my machine every time. Not sure what has happened.

Actually, I'm curious of why Nix would pick duplo up as I haven't explicitly pushed it that way. This may be too much to ask, but is there a way to remove it from the registry?

**Comment by peti** [comment]
Nixpkgs distribute every package that's available on Hackage.

**Comment by kenhkan** [comment]
Oh. I see. Sorry for sounding very ignorant when it comes to Nix as I haven't had too much experience with it. It seems that I couldn't find that particular job on nixos' hydra here: http://hydra.nixos.org/job/nixpkgs/haskell-updates/haskellngPackages.duplo.x86_64-linux and the version seems to run fine in most of the jobs listed there. Am I looking at the right place?

**Comment by peti** [comment]
The build logs on hydra.nixos.org don't show the error because I disabled the test suite: https://github.com/NixOS/nixpkgs/commit/707f75ddabb6fb69ccc7381c3a39325f9a47670f. The build log I linked to is from hydra.cryp.to, which is my own server. I use that to test the state of the Haskell package set before pushing a new version to the official repository.

**Comment by kenhkan** [comment]
Ah got it. I'd love to make this work, but I don't even know where to begin. The tests are running fine at that version as well as the current version. The preconditions are actually necessary because it would otherwise be an improper Component.io name. If it is not too much to ask, is it possible for you to run the most recent version at 1.8.0 on hydra?

**Comment by peti** [comment]
I don't believe that it makes any difference where those tests run. Whether they fail or not is simply a matter of probabilities. For every possible sample that this test might be run with, there exists a probability that this particular sample is generated by QuickCheck. The sample space is partitioned into two sets: those elements that satisfy your pre-condition and those that don't. This means that we can determine a probability for QuickCheck to generate a sample that leaves the test inconclusive (because it doesn't satisfy the pre-condition), and consequently there is a probability that such an inconclusive sample is picked, say, 100 times in a row. If that happens, then QuickCheck will abort the test and report a failure (which is what happened in the build log we saw).

The test didn't fail because QuickCheck managed to prove it wrong -- it failed because QuickCheck didn't manage to generate enough valid samples to run the test at all. Clearly, the test will succeed fine in, say, 99 out of 100 times it's run, but my guess is that there will be intermittent failures because of that issue. Now, intermittent failures is the one thing we don't want on our CI environment, because these kind of false positives cause significant effort to the Nixpkgs maintainers. Every time that test fails, there's going to be an e-mail sent to someone, that person has to read the logs, evaluate the situation, write a bug report, etc. That is a lot of work. 

If you are confident that you've understood the reason for that test failure and if you are certain that those issues have been remedied, then I'll be happy to re-enable the test suite in Nixpkgs. But I rather not enable the test suite in our distribution's central builds as a kind of debugging attempt, just so that we can check whether it fails again.

**Comment by kenhkan** [comment]
Hey @peti , I'm really sorry for having gone missing. I'll actually stop pushing to Hackage. Since Hackage doesn't allow packages to be removed, can you somehow put a tag to prevent fetching duplo for tests? Thank you! And sorry for the inconvenience.

**Comment by peti** [comment]
http://hackage.haskell.org/package/duplo/maintainYou may want to mark your package as deprecated  on Hackage:

**Comment by peti** [comment]
You may want to mark your package as deprecated on Hackage: http://hackage.haskell.org/package/duplo/maintain.

**Comment by kenhkan** [comment]
Done. Thank you for the suggestion. I wasn't aware of that. Closing this issue now.
